(add-to-list 'load-path (expand-file-name "~/archlinux-scripts/emacs"))
(require 'go-mode-autoloads)
(require 'auto-install)
(require 'typescript)
(add-to-list 'auto-mode-alist '("\\.ts\\'" . typescript-mode))
(require 'tss)
;; Key binding
(setq tss-popup-help-key "C-:")
(setq tss-jump-to-definition-key "C->")
(setq tss-implement-definition-key "C-c i")
(tss-config-default)
